### ISSUE TITLE
Render Python docstrings using comment color

### ISSUE THREAD

**Issue by tactlessfish** [cs50/render50#72]
Hello and thanks for creating this tool; it's super convenient! I have a suggestion for Python syntax highlighting.

Currently, Python docstrings render in red, the same color as strings. This can be misleading about the docstring's purpose in the source code.
![image](https://user-images.githubusercontent.com/29507110/114274977-d3d2b600-99ee-11eb-8e90-82f12743906f.png)

I suggest that they render in cyan instead, the same color as doc comments in Java.
![image](https://user-images.githubusercontent.com/29507110/114275484-9ec76300-99f0-11eb-94f1-b4f7bf87b1d5.png)

**Comment by dmalan** [comment]
Ah, thanks! I think we'd prefer not to override manually specific colors, since we're simply relying on Pygments's built-in styles, https://pygments.org/demo/, but we've added a `-S` flag via which you can choose a different style now!

https://cs50.readthedocs.io/render50/#override-syntax-highlighting

You might need to do `pip3 install render50 --upgrade` first. Or use https://render.cs50.io/!

**Comment by tactlessfish** [comment]
Got it, thank you!
